#!/usr/bin/env node
// Slice an OpenAPI (v3) / Swagger (v2) contract down to the endpoints one feature needs.
// Usage: node contract-slice.mjs <url-or-path> <out.md> "GET /pet/{petId}" "POST /pet" ...
//
// Why: reading a whole contract costs tens of thousands of tokens and invites invented
// shapes. This emits only the requested operations with $refs inlined, so the exact
// request/response schema is on the page and nothing has to be guessed.

import { writeFileSync, readFileSync, existsSync, mkdirSync } from "node:fs"
import { dirname } from "node:path"

const [src, out, ...wanted] = process.argv.slice(2)
if (!src || !out || wanted.length === 0) {
  console.error('Usage: contract-slice.mjs <url-or-path> <out.md> "GET /path" ["POST /path" ...]')
  process.exit(1)
}

const spec = await load(src)
const isV2 = typeof spec.swagger === "string"
const seen = new Set()

const ops = wanted.map((w) => {
  const [rawMethod, ...rest] = w.trim().split(/\s+/)
  const method = rawMethod.toLowerCase()
  const path = rest.join(" ")
  const op = spec.paths?.[path]?.[method]
  if (!op) throw new Error(`Not in contract: ${w}. Available: ${Object.keys(spec.paths ?? {}).length} paths.`)
  return { method: rawMethod.toUpperCase(), path, op }
})

const lines = [
  `# Contract slice`,
  ``,
  `Source: \`${src}\``,
  `Base: ${(isV2 ? [spec.host && `${spec.schemes?.[0] ?? "https"}://${spec.host}${spec.basePath ?? ""}`] : spec.servers?.map((s) => s.url))?.filter(Boolean).join(", ") || "n/a"}`,
  ``,
  `Generated by \`contract-slice.mjs\` — exact shapes, $refs inlined. Do not invent fields not listed here.`,
  ``,
]

for (const { method, path, op } of ops) {
  lines.push(`---`, ``, `## ${method} ${path}`, ``)
  if (op.operationId) lines.push(`operationId: \`${op.operationId}\``, ``)
  if (op.summary) lines.push(op.summary, ``)

  const params = [...(spec.paths[path].parameters ?? []), ...(op.parameters ?? [])].map(deref)
  const bodyParam = isV2 ? params.find((p) => p.in === "body") : null
  const plain = params.filter((p) => p.in !== "body")
  if (plain.length) {
    lines.push(`### Parameters`, ``, `| Name | In | Required | Type | Notes |`, `|---|---|---|---|---|`)
    for (const p of plain) {
      const s = deref(p.schema ?? p)
      lines.push(`| \`${p.name}\` | ${p.in} | ${p.required ? "yes" : "no"} | ${cell(typeName(s))} | ${cell(notes(s))} |`)
    }
    lines.push(``)
  }

  const body = bodyParam?.schema ?? pickSchema(op.requestBody?.content)
  if (body) {
    lines.push(`### Request body`, ``, "```json", JSON.stringify(shape(body), null, 2), "```", ``)
    lines.push(...requiredNote(body))
  }

  lines.push(`### Responses`, ``)
  for (const [code, res] of Object.entries(op.responses ?? {})) {
    const r = deref(res)
    const schema = isV2 ? r.schema : pickSchema(r.content)
    lines.push(`**${code}** — ${r.description ?? ""}`.trim(), ``)
    if (schema) {
      lines.push("```json", JSON.stringify(shape(schema), null, 2), "```", ``)
      lines.push(...requiredNote(schema))
    }
  }
  if (op.security ?? spec.security) lines.push(`Auth: ${JSON.stringify(op.security ?? spec.security)}`, ``)
}

mkdirSync(dirname(out), { recursive: true })
const text = lines.join("\n")
writeFileSync(out, text)
console.log(`Wrote ${out} — ${ops.length} operation(s), ${text.length} chars.`)

// ---------- helpers ----------

async function load(input) {
  if (existsSync(input)) return JSON.parse(readFileSync(input, "utf8"))
  const res = await fetch(input, { headers: { accept: "application/json" } })
  if (!res.ok) throw new Error(`Fetch failed ${res.status} for ${input}`)
  return res.json()
}

function deref(node, depth = 0) {
  if (!node || typeof node !== "object" || depth > 50) return node ?? {}
  if (!node.$ref) return node
  const path = node.$ref.replace(/^#\//, "").split("/")
  let cur = spec
  for (const seg of path) cur = cur?.[seg.replace(/~1/g, "/").replace(/~0/g, "~")]
  return deref(cur, depth + 1)
}

function pickSchema(content) {
  if (!content) return null
  const key = Object.keys(content).find((k) => k.includes("json")) ?? Object.keys(content)[0]
  return key ? deref(content[key].schema) : null
}

function typeName(s) {
  const d = deref(s)
  if (d.enum) return `enum(${d.enum.join(" | ")})`
  if (d.type === "array") return `${typeName(d.items)}[]`
  return [d.type ?? "object", d.format && `<${d.format}>`].filter(Boolean).join("")
}

// Markdown tables split on "|" — enum unions must not break the row.
function cell(text) {
  return String(text).replace(/\|/g, "\\|")
}

function notes(s) {
  const d = deref(s)
  return [d.nullable && "nullable", d.default !== undefined && `default: ${JSON.stringify(d.default)}`, d.description]
    .filter(Boolean)
    .join("; ")
}

// Render a schema as an annotated example object: every leaf becomes "<type> required|optional".
function shape(schema, depth = 0) {
  const s = deref(schema)
  if (depth > 12) return "<circular>"
  if (s.allOf) return s.allOf.map((x) => shape(x, depth + 1)).reduce((a, b) => Object.assign({}, a, b), {})
  const branch = s.oneOf?.[0] ?? s.anyOf?.[0]
  if (branch) return shape(branch, depth + 1)
  if (s.type === "array") return [shape(s.items ?? {}, depth + 1)]
  if (s.type === "object" || s.properties) {
    const req = new Set(s.required ?? [])
    const obj = {}
    for (const [k, v] of Object.entries(s.properties ?? {})) {
      const d = deref(v)
      const isLeaf = d.properties === undefined && d.type !== "array" && !d.allOf && !d.oneOf && !d.anyOf
      obj[k] = isLeaf ? `${typeName(d)} ${req.has(k) ? "REQUIRED" : "optional"}` : shape(d, depth + 1)
    }
    if (s.additionalProperties) obj["[key: string]"] = shape(s.additionalProperties, depth + 1)
    return obj
  }
  return typeName(s)
}

function requiredNote(schema) {
  const s = deref(schema)
  const target = s.type === "array" ? deref(s.items) : s
  return target.required?.length ? [`Required: ${target.required.map((r) => `\`${r}\``).join(", ")}`, ``] : []
}
